app01/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', views.home, name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)', views.market, name='market'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^sub_cart/', views.sub_cart, name='sub_cart'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^register/', views.register, name='register'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^login/', views.login, name='login'),
    url(r'^register_check/', views.register_check, name='register_check'),
    url(r'^pcgetcaptcha/', views.pcgetcaptcha, name='pcgetcaptcha'),
    url(r'^add_cart_num/', views.add_cart_num, name='add_cart_num'),
    url(r'^sub_cart_num/', views.sub_cart_num, name='sub_cart_num'),
    url(r'^change_select/', views.change_select, name='change_select'),
    url(r'^all_select/', views.all_select, name='all_select'),
    url(r'^receiver/', views.receiver, name='receiver'),
    url(r'^create_order/', views.create_order, name='create_order'),
    url(r'^submit_order/', views.submit_order, name='submit_order'),
]

axfhz1805/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("app01.urls", namespace="axf")),
    url(r'^$', views.home)
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=0" />
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="//gtms04.alicdn.com/tps/i4/TB1_oz6GVXXXXaFXpXXJDFnIXXX-64-64.ico" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% block extCSS %}

    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block header %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}



<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'js/md5.js' %}"></script>
<script src="{% static 'js/base.js' %}"></script>
{% block extJS %}

{% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/base_main.css' %}">
{% endblock %}

{% block header %}
    <header>

    </header>
{% endblock %}


{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt><span></span></dt>
                <dd>主页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' 104749 0 0 %}" class="market">
            <dl>
                <dt><span></span></dt>
                <dd>闪购</dd>
            </dl>
        </a>
       <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}