app01/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', views.home, name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)', views.market, name='market'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^sub_cart/', views.sub_cart, name='sub_cart'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^register/', views.register, name='register'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^login/', views.login, name='login'),
    url(r'^register_check/', views.register_check, name='register_check'),
    url(r'^pcgetcaptcha/', views.pcgetcaptcha, name='pcgetcaptcha'),
    url(r'^add_cart_num/', views.add_cart_num, name='add_cart_num'),
    url(r'^sub_cart_num/', views.sub_cart_num, name='sub_cart_num'),
    url(r'^change_select/', views.change_select, name='change_select'),
    url(r'^all_select/', views.all_select, name='all_select'),
    url(r'^receiver/', views.receiver, name='receiver'),
    url(r'^create_order/', views.create_order, name='create_order'),
    url(r'^submit_order/', views.submit_order, name='submit_order'),
]

axfhz1805/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("app01.urls", namespace="axf")),
    url(r'^$', views.home)
]

templates/user/login.html
{%  extends 'base.html' %}
{% load static %}

{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{%  static 'app01/user/login.js' %}"></script>
{% endblock %}



{% block content %}

        <div style="padding: 18px">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">用户名:</label><span id="nameError"></span>
            <input type="text" class="form-control" id="username" name="username" placeholder="请输入用户名">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">密码:</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="请输入您的密码">
        </div>
        <span style="color:red;" id="error_msg"></span>
            <div id="popup-captcha"></div>

        <button type="submit" class="btn btn-default" id="login_button"><span id="make_md5">登录</span></button>
        <a href="{% url 'axf:register' %}" role="button" class="btn btn-default">注册</a>
        </div>
<script src="http://static.geetest.com/static/tools/gt.js"></script>

{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% load static %}
{% block extJS %}
    {{ block.super }}
    <script src="{% static 'app01/user/register.js' %}"></script>
{% endblock %}


{% block content %}
    <form style="padding: 18px" action="{% url 'axf:register_check' %}" method="post" enctype="multipart/form-data" onsubmit="return formsubmit()">
        {% csrf_token %}
        <div class="form-group has-feedback">
            <label for="exampleInputEmail1">用户名:</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="请输入用户名">
            <span id="nameError"></span>
        </div>
        <div class="form-group has-feedback">
            <label for="exampleInputPassword1">密码:</label>
            <input type="password" class="form-control" id="password1" placeholder="请设置您的密码">
        </div>
        <div class="form-group has-feedback">
            <label for="exampleInputPassword1">确认密码:</label> <span id="errorMsg"></span>
            <input type="password" class="form-control" id="password2" name="password" placeholder="请确认您的密码">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">邮箱:</label>
            <input type="email" class="form-control" id="exampleInputEmail1" name="email" placeholder="请输入您的邮箱地址">
        </div>
        <div class="form-group">
            <label for="exampleInputFile">头像:</label>
            <input type="file" name="imgFile" id="exampleInputFile">
            <p class="help-block">请在此处上传您的头像</p>
        </div>

        <button type="submit" class="btn btn-default">提交</button>
    </form>
{% endblock %}