app01/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', views.home, name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)', views.market, name='market'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^sub_cart/', views.sub_cart, name='sub_cart'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^register/', views.register, name='register'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^login/', views.login, name='login'),
    url(r'^register_check/', views.register_check, name='register_check'),
    url(r'^pcgetcaptcha/', views.pcgetcaptcha, name='pcgetcaptcha'),
    url(r'^add_cart_num/', views.add_cart_num, name='add_cart_num'),
    url(r'^sub_cart_num/', views.sub_cart_num, name='sub_cart_num'),
    url(r'^change_select/', views.change_select, name='change_select'),
    url(r'^all_select/', views.all_select, name='all_select'),
    url(r'^receiver/', views.receiver, name='receiver'),
    url(r'^create_order/', views.create_order, name='create_order'),
    url(r'^submit_order/', views.submit_order, name='submit_order'),
]

axfhz1805/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("app01.urls", namespace="axf")),
    url(r'^$', views.home)
]

templates/mine/mine.html
{% extends 'base_main.html' %}

{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app01/mine/mine.css' %}">
{% endblock %}


{% block content %}
    <div id="mine">
        <div class="fixed">

            {% if user %}
                <img src="{{ img_path }}" alt="#">
            {% else %}
                <span style="color: red" class="glyphicon glyphicon-user"></span>
            {% endif %}

            <p>
                {% if user %}
                    <a href="#">{{ user.u_name }}</a>
                {% else %}
                    <a href="{% url 'axf:login' %}">未登录</a>
                {% endif %}
            </p>

            <p>
                <span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
            {% if user %}

                {% else %}
                 <a id="regis" href="{% url 'axf:register' %}">注册</a>
            {% endif %}

            <p>
                <span class="glyphicon glyphicon-heart"></span>
                商品收藏
            </p>
        </div>
        <section class="mine">
            <p>
                <span>我的订单</span>
                <a href="#">查看全部订单&gt;</a>
            </p>
            <nav id="nav">
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-usd"></span>
                                    {% ifnotequal wait_pay 0 %}
                                        <span style="background: red " class="badge">{{ wait_pay }}</span>
                                    {% endifnotequal %}
                                </dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-envelope"></span>
                                    {% ifnotequal wait_receiver 0 %}
                                        <span style="background: red " class="badge">{{ wait_receiver }}</span>
                                    {% endifnotequal %}

                                </dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-pencil"></span>
                                    {% ifnotequal wait_calk 0 %}
                                        <span style="background: red " class="badge">{{ wait_calk }}</span>
                                    {% endifnotequal %}
                                </dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-transfer"></span>
                                    {% ifnotequal wait_after 0 %}
                                        <span style="background: red " class="badge">{{ wait_after }}</span>
                                    {% endifnotequal %}
                                </dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                                <dd>积分商城</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-asterisk"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>


                </ul>

            </menu>
            <p>
                {% if user %}
                <a href="{% url 'axf:logout' %}">退出账号</a>
                {% endif %}

            </p>
        </section>

    </div>

{% endblock %}